export const EMPLOYEES=[{
    "id": 1,
    "first_name": "Haskel",
    "last_name": "Frankiewicz",
    "email": "hfrankiewicz0@cam.ac.uk",
    "gender": "Male",
    "mobile": "7686729923"
  }, {
    "id": 2,
    "first_name": "Aaron",
    "last_name": "Bavister",
    "email": "abavister1@bbb.org",
    "gender": "Male",
    "mobile": "3981842499"
  }, {
    "id": 3,
    "first_name": "Taite",
    "last_name": "Davers",
    "email": "tdavers2@exblog.jp",
    "gender": "Male",
    "mobile": "8089361633"
  }, {
    "id": 4,
    "first_name": "Kim",
    "last_name": "Padbery",
    "email": "kpadbery3@dedecms.com",
    "gender": "Male",
    "mobile": "2224538391"
  }, {
    "id": 5,
    "first_name": "Sherm",
    "last_name": "Camelia",
    "email": "scamelia4@facebook.com",
    "gender": "Male",
    "mobile": "3569084949"
  }, {
    "id": 6,
    "first_name": "Alvan",
    "last_name": "Dabbes",
    "email": "adabbes5@gravatar.com",
    "gender": "Male",
    "mobile": "4289716784"
  }, {
    "id": 7,
    "first_name": "Abbe",
    "last_name": "Hanalan",
    "email": "ahanalan6@cyberchimps.com",
    "gender": "Male",
    "mobile": "5228580026"
  }, {
    "id": 8,
    "first_name": "Glendon",
    "last_name": "Domingues",
    "email": "gdomingues7@psu.edu",
    "gender": "Male",
    "mobile": "1440843597"
  }, {
    "id": 9,
    "first_name": "Yurik",
    "last_name": "MacKimmie",
    "email": "ymackimmie8@shinystat.com",
    "gender": "Male",
    "mobile": "3932196023"
  }, {
    "id": 10,
    "first_name": "Ermengarde",
    "last_name": "Dugdale",
    "email": "edugdale9@storify.com",
    "gender": "Female",
    "mobile": "5856265912"
  }]